import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/Provider";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const userId = session?.user?.id;

  return (
    <html lang="en">
      <body>
        <Provider userId={userId}>
          <div>
            <Navbar />
          </div>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
