import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/Provider";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div>
            <Navbar />
          </div>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
